version: "3.3"
services:
  nginx:
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}_nginx.${CI_PIPELINE_ID}
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - internal

  php:
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}_php.${CI_PIPELINE_ID}
    ports:
      - "9000:9000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
