version: "3.3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
