image: docker:latest
services:
  - docker:dind

stages:
  - build
  - push
  - pull

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_nginx.$CI_PIPELINE_ID .
  tags:
    - docker

push:
  stage: push
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_nginx.$CI_PIPELINE_ID
  tags:
    - docker

pull:
  stage: pull
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_nginx.$CI_PIPELINE_ID
    - docker run -d --rm --name=${CI_COMMIT_REF_NAME} -p 8080:80 -i $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_nginx.$CI_PIPELINE_ID
  tags:
    - docker